steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/snapvault-backend-dev/backend:$SHORT_SHA
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/snapvault-backend-dev/backend:$SHORT_SHA

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - snapvault-backend-dev
      - --image=asia-south1-docker.pkg.dev/$PROJECT_ID/snapvault-backend-dev/backend:$SHORT_SHA
      - --region=asia-south1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=5
      - --add-cloudsql-instances=snapvault-489304:asia-south1:snapvault-dev
      - --set-secrets=DB_USER=DB_USER_DEV:latest,DB_PASS=DB_PASSWORD_DEV:latest,DB_NAME=DB_NAME_DEV:latest,REDIS_URL=REDIS_URL_DEV:latest,JWT_SECRET=JWT_SECRET_DEV:latest,AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID_DEV:latest,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY_DEV:latest,AWS_REGION=AWS_REGION_DEV:latest,AWS_S3_BUCKET=S3_BUCKET_DEV:latest,REKOGNITION_COLLECTION=REKOGNITION_COLLECTION_DEV:latest,RAZORPAY_KEY_ID=RAZORPAY_KEY_ID_DEV:latest,RAZORPAY_KEY_SECRET=RAZORPAY_KEY_SECRET_DEV:latest,RAZORPAY_WEBHOOK_SECRET=RAZORPAY_WEBHOOK_SECRET_DEV:latest,SMTP_HOST=EMAIL_HOST_DEV:latest,SMTP_PORT=EMAIL_PORT_DEV:latest,SMTP_USER=EMAIL_USER_DEV:latest,SMTP_PASS=EMAIL_PASS_DEV:latest,FIREBASE_SA_JSON=FIREBASE_SA_JSON_DEV:latest
      - --set-env-vars=NODE_ENV=development,DB_SOCKET_PATH=/cloudsql/snapvault-489304:asia-south1:snapvault-dev,ALLOWED_ORIGINS=http://localhost:3000,https://dev.snaplivo.in/

options:
  logging: CLOUD_LOGGING_ONLY
